### PR TITLE
Fixed exports for rollup & fixed vars not defined

### PR DESCRIPTION
**Pull request by KaruroChori**
Fixed issue #322 with rollup.js (and as such vite) by exporting all symbols. 
Fixed few more variables which were raising exceptions..

### CODE REVIEW

**Comment by jagenjo** [comment]
ok, accepted but not very fond of some of the rules in the linter, like breaking conditions in several lines.

**Comment by KaruroChori** [comment]
I just missed the absurd amount of changes which were made.

I have not set up the linter manually, it was already configured as such in the file _.prettierrc_ which was last edited 4 years ago.
If you think that should be different, please update it according to your preferences, so that when linted the resulting code is compliant with your stylistic guidelines.

**Comment by lathanbritz** [comment]
running in to this issue here was the fix ever implemented here?

**Comment by jagenjo** [comment]
@KaruroChori yeah, somebody added that prettierrc some time ago and did the linting and well, it destroyed most conditions to my liking. But I dont know how prettierrc works so I never changed it.

@lathanbritz Im lost, whats rollup.js?

**Comment by lathanbritz** [comment]
Assume it's the config to the vite instance where I'm running this inside. Vite seems to compile differently at dev vs prod time... so was hoping auth of this issue could attach what they did in vite to get this working. Still scratching my head how to achieve what they claimed to have solved here.

**Comment by lathanbritz** [comment]
dope actually a little digging and found what he did https://github.com/KaruroChori/node-paradise/blob/main/vite.config.ts

**Comment by KaruroChori** [comment]
>>>https://github.com/KaruroChori/node-paradise/blob/main/vite.config.ts
lol, I guess I should have cleaned up a bit that file before the public commit :smile: . I am sure not all those options are required at the same time. I was desperate and just used every bullet I had.

The other piece to fix that specific problem was the addition of the exports at the end of litegraph.js

```
if (typeof exports != "undefined") {
    exports.LiteGraph = this.LiteGraph;
    exports.LGraph = this.LGraph;
    exports.LLink = this.LLink;
    exports.LGraphNode = this.LGraphNode;
    exports.LGraphGroup = this.LGraphGroup;
    exports.DragAndScale = this.DragAndScale;
    exports.LGraphCanvas = this.LGraphCanvas;
    exports.ContextMenu = this.ContextMenu;
}```

**Pull request closed without merging**
