### PR TITLE
Fixed DTS for registered_node_types, node_types_by_file_extension, an…

### PR DESCRIPTION
**Pull request by julien-moreau**
…d Nodes in LiteGraph to properly take LGraphNodeConstructor instead of LGraphNode.

### CODE REVIEW

**Comment by jagenjo** [comment]
I have no idea about typescript so I will guess it is a valid fix...

**Comment by julien-moreau** [comment]
Ahah no worry, thanks @jagenjo 

Basically, setting LGraphNode instead of LGraphNodeConstructor means that the .Nodes property contains instances of LGraphNode and not constructor references of LGraphNode

**Comment by julien-moreau** [comment]
Do you think a 0.7.3 would be available soon on npm?

**Comment by jagenjo** [comment]
I usually only update when some important changes have been made, I can push a new one if you need it.

**Comment by julien-moreau** [comment]
I understand :)
Would be awesome if you can as the project (https://github.com/BabylonJS/Editor) is referencing litegraph.js from npm and is developed using TypeScript :)
Thanks a lot!

**Pull request merged**
