### PR TITLE
Conversion to ES6 Classes (Stable, Major)

### PR DESCRIPTION
**Pull request by ghost**
This PR is to pull:

* Split apart litegraph.js file into multiple class-oriented files.
* Converted to ES6 classes for all of core and nodes.
* Ran code through a pretty-printer, verifying no modifications to content were made.
* Made several HTML and CSS validation improvements.
* Identified a uninitialized variable bug.
* Commented out SillyClient class in nodes\network.js and in HTML
* Updated README.md's etc.
* Updated utils/ build lists to reflect multiple class files of current state.

I made as few modifications to the code beyond that as possible, and each one was made as a separate commit.

### CODE REVIEW

**Comment by jagenjo** [comment]
Hey, can you restore the TS files? they are important to other people.

**Comment by ghost** [comment]
Hi Javi,

I put the litegraph.d.ts file back into the folder.

My background:
I'm familiar with python servers, know a little of node.js, apt, pip, venv,
an online beautifier, asm, C, D, JS, Python, CSS, HTML5, web design and
development, restful interfaces, comfyui, AI models, llama-cpp-python, LLM
and neural network theory, etc.

If you want a restoration (like restoring an old axe) done in TS, maybe put
me in touch with someone familiar with more of your toolchain who wants to
work together on it - I presume you aren't that invested anymore.

But I was going to focus on fixing the events infrastructure, separate
concerns a bit so it was more maintainable, and then start extracting
features from HTML Canvas to HTML+SVG.

I can be reached on Discord as mr_pebble, or on Element as
@mr_pebble:matrix.org ***@***.***_pebble:matrix.org>

Regards,
Daniel

**Comment by moritz89** [comment]
Regarding the TS file, we use litegraph.js in our Angular project (TS) and would be open to help if anything specific comes up. From a technical side, we mainly use the presentation layer of litegraph.js and execute the graph in a separate engine.

Currently we mainly focus on packaging a release after every MR so that they are easily used from NPM: https://www.npmjs.com/package/@inamata-co/litegraph.js

**Comment by ghost** [comment]
Hi Moritz,

Nice to e-meet you.  To catch you up in case it helps:

https://github.com/jagenjo/litegraph.js/pull/455

I basically wrote a large part of an update for LiteGraph.js in JS from
2011 to ES6 and am continuing to work on the next step.  My intent was to
have a functioning modern flow graph library, but I don't currently use TS
for anything, don't use Angular, and don't use npm.

In the interest of LiteGraph serving everyone properly, it *does *seem to
be appropriate to support the variety of uses of it in ways that are
practicable, but I myself am writing this as a matter of hobby and I'm not
sure I'm committed to learning a new language and toolchain to do so given
that fact.  So I asked Javi to put me in touch with someone I could discuss
this with who could fill the role of working with me to support that side
of things.

If that isn't you, that's fine too, but do you happen to know anyone who
does seem like a good fit for that?

Regards,
Daniel

My background:
> I'm familiar with python servers, know a little of node.js, apt, pip,
> venv, an online beautifier, asm, C, D, JS, Python, CSS, HTML5, web design
> and development, restful interfaces, comfyui, AI models, llama-cpp-python,
> LLM and neural network theory, etc.
>
> If you want a restoration (like restoring an old axe) done in TS, maybe
> put me in touch with someone familiar with more of your toolchain who wants
> to work together on it - I presume you aren't that invested anymore.
>
> But I was going to focus on fixing the events infrastructure, separate
> concerns a bit so it was more maintainable, and then start extracting
> features from HTML Canvas to HTML+SVG.
>
> I can be reached on Discord as mr_pebble, or on Element as
> @mr_pebble:matrix.org ***@***.***_pebble:matrix.org>
>

**Comment by moritz89** [comment]
The TS and npm functionality / work can be built on top of your changes without you requiring to interact with it. In order to use JS code in TS, its tooling and Angular, only the type definition .d.ts files have to be written. I'd gladly keep these up.-to-date with changes to the JS files. Regarding the npm releases, I use an automated approach that only requires running a single command.

A workflow that could work is soon after an MR is accepted, me and my team would update the .d.ts file if required and then publish a release. This would mirror the existing work that I do to publish npm releases.

The only question I'd have is whether I should continue publishing in our npm package ([@inamata-co/litegraph.js](https://www.npmjs.com/package/@inamata-co/litegraph.js)) or to publish in Javi's original npm package ([litegraph.js](https://www.npmjs.com/package/litegraph.js))?

**Comment by jagenjo** [comment]
Hi all:

I think this is a nice PR and I want to accept it, as it is always nice to clear the code a little.
My only concern is that this is more than a simple refactor, some features are dissapearing, which is a no-go as people depend on them.
I created a release with the current version so we can talk about changes.
For instance, I wont accept moving to SVG, mostly because that closes the door to many cool features (like rendering the graph using WebGL, which Im using in other projects).
I will leave this PR for a while, testing it, and if it seems to work fine, I will accept it.
In the future it will be good to keep PRs smaller, as this one is scary, but I appreciate the effort.

Cheers

**Comment by ghost** [comment]
Javi,

Yeah, I didn't see a smaller cut-off to perform the transfer to ES6 without
converting the whole thing given the dependencies and connections and
such.  I do appreciate it was a rather huge step, and my next steps are all
quite a lot smaller.

I do hope we can effect changes to this so none or very little of the
features are lost before/as/shortly-after it becomes main-line.

In particular, the utils, npm, TS, etc. were already mentioned.

My next PR will then be some minor patching to classes to get various
things more right.

You are welcome to suggest particular changes you'd like to see.

**Comment by ghost** [comment]
Javi,

I just realized the PR is continuing to take updates from my main branch, rather than the branch I intended it to come off of.
It is only intended to be up to https://github.com/jagenjo/litegraph.js/pull/455/commits/f195a96b95ae4abddb5a506216cf15c7d39ba6e0

**Comment by ghost** [comment]
I have this frozen and will not push another change until I have more instructions.  I can rewind it, leave it, finish, whatever you like Javi.

**Comment by ghost** [comment]
https://github.com/jagenjo/litegraph.js/pull/462

**Pull request closed without merging**
