### PR TITLE
replacing slider precision harcoded value

### PR DESCRIPTION
**Pull request by Guillaume-Fgt**
#409 

Following your answer @jagenjo , here is the PR. Thank you for your quick answer.

### CODE REVIEW

**Comment by jagenjo** [comment]
instead of w.options.precision !== undefined
please use != null, as in your condition null would be a valid value.

**Comment by Guillaume-Fgt** [comment]
For the combo case, the value is also checked using `undefined`. Do you want me to change this one too?

**Comment by jagenjo** [comment]
no need, but you did the fix wrong, !== null means undefined is a valid value, just != null controls undefined and null as possible conditions.

**Comment by Guillaume-Fgt** [comment]
thank you for you patience, I am not comfortable with JavaScript, still a lot to learn...

**Comment by jagenjo** [comment]
Thanks to you.

**Pull request merged**
