### PR TITLE
Updated npm publish structure

### PR DESCRIPTION
**Pull request by kriffe**
- Included build catalogue and correct package.json for npm publish

- Included license file

- Added grid image as data url

- Added node express web server for dev. Start with "npm start" (requires nodejs 8+)

### CODE REVIEW

**Comment by jagenjo** [comment]
Also, before my project didnt have any dependency, now it has 40 node_modules, I have the feeling that you are overengineering, I like to keep stuff light and simple. I understand that using grunt makes it more friendly, but running a pythong script wasnt so complext after all.

**Comment by kriffe** [comment]
It should only be dev-depencenies I believe and should not be included when in production (with local npm install --production or fetch from npm install litegraph.js). 

The purpose was to make sure that everything is bundled inside the project when developing. The python scripts didn't work for me due to global references to '/usr/local/bin/compiler.jar' that perhaps is a global install of google closure compiler?

But I understand, and will try to reduce it. Its a good principle. Many of the dev tools can be added globally on my side instead.

**Comment by jagenjo** [comment]
I like the idea if they are optional, as always, giving freedom to the end-user is the best choice.

the compiler.jar yes, maybe it would be nice to have a way to install it easily, like a npm or something.

thanks again for the effort Kristofer

**Comment by kriffe** [comment]
Have you tried running the installation direct from npm instead of git (npm install litegraph.js) when you include it in another repo (version 0.3.0)? The result is only theese files below in the node_modules/litegraph.js folder:

image

Build contains the litegraph.js and litegraph.bundle.js

**Comment by kriffe** [comment]
Regarding the compiler: perhaps it could be refered to the compiler in node_modules if google closure compiler is used? The path is:
```
litegraph.js\node_modules\google-closure-compiler\compiler.jar
```

**Comment by kriffe** [comment]
A thought on the many node_modules. 

I usually don't look so much in the node_modules folder since its not a flat dependency structure any more (sinve npm v3). Hence all sub dependencies are shown on top level and it gets quite messy there. But since the node_modules isn't included in commits to git or version control I find it reduces the ammount of code in the projects.

Like the jquery 1.6.2 in externals could be left out and will automatically updated patches if the the library is referenced in package.json with the appropriate flag (^/~, etc) instead of included. (see https://docs.npmjs.com/files/package.json#dependencies for more info on semver version control)

**Comment by jagenjo** [comment]
Yes, is the google closure compiler, so if it can be installed as a module that would make things much easier. Usually for me the problem is that if I use this compiler in other projects (as I do) I end up having several installations spread in my machine, but I understand the convenience.

Removing manual dependencies is always good anyway.

**Pull request merged**
