### PR TITLE
Add Ctrl+Shift+V to paste with unselected nodes connected

### PR DESCRIPTION
**Pull request by tianlang0704**
Just adding a ctrl + shift + v short cut for pasting with the unselected nodes connected so it's easier to do mass copy paste.
image

### CODE REVIEW

**Comment by atlasan** [comment]
This would paste copied nodes and connect them same as the originals are connected (to unselected nodes too)?
Is that it?
Seems a quite nice feature!
Just would like to be sure that doesn't break previous behaviors. Eg. what about destination links where only one input is allowed?

**Comment by atlasan** [comment]
I would anyway place a boolean config parameters on top of lib file, to condition every new feature to be enabled or not. This to try to always be retrocompatibile.

**Comment by moritz89** [comment]
1. It would be very useful for this to be documented as it is non-obvious behavior (e.g., guides/shortcuts.md with a link from the main readme)
2. Optionally it would be useful to have a test to ensure that it doesn't break existing behavior and actually copies all connections correctly

**Comment by atlasan** [comment]
Yes, agree with updating the doc about available shortcuts.
Adding some examples graph in the editor with comments and nodes it's another good place.

The keys inputs should be decoupled and placed in a config file with the current keys combination. Would be great that way.
At the now some config boolean is placed for new behaviors.

**Comment by tianlang0704** [comment]
> This would paste copied nodes and connect them same as the originals are connected (to unselected nodes too)? Is that it? Seems a quite nice feature! Just would like to be sure that doesn't break previous behaviors. Eg. what about destination links where only one input is allowed?

Ohh! I didn't think of connecting the output of the copied nodes to the inputs of those unselected nodes. It's only connecting the outputs of those unselected ones to the inputs of the newly pasted nodes at the moment, but I see it's a good idea to connect the new outputs if those unselected inputs can accept multiple outputs.

 

> I would anyway place a boolean config parameters on top of lib file, to condition every new feature to be enabled or not. This to try to always be retrocompatibile.
OK, I see a lot of switches at the top of litegraph.js, is inserting one at the bottom of those switches a good idea?



> 1. It would be very useful for this to be documented as it is non-obvious behavior (e.g., guides/shortcuts.md with a link from the main readme)
> 2. Optionally it would be useful to have a test to ensure that it doesn't break existing behavior and actually copies all connections correctly
I'm only adding a little bit onto the default ctrl+v default pasting behavior. I didn't find anything about shortcuts in the guides/README.md, is it a good idea for me to start a new section for it?



So TODO for now:
1. Add new outputs to old inputs check and connection.
2. Add global swtich for this new feature
3. Add shortcut section in guides/README.md
4. Add test for this new feature

**Comment by atlasan** [comment]
@tianlang0704  Now Isee, your proposal of working only with outputs of unselected nodes was good

Multi-input nodes are not native, so maybe could check for an existing event method (a new one, "onDuplicatedSourceNode" or something.), that method could than add a slot, make an array or whatever.

The global switch should stay off in the library to be compatible. It could be true in the `defaults` file of the demo editor to show it off.

**Pull request merged**
