### PR TITLE
feat: support typescript

### PR DESCRIPTION
**Pull request by NateScarlet**
add type definitions

### CODE REVIEW

**Comment by jagenjo** [comment]
wow, amazing, are you using LiteGraph with typescript?

**Comment by NateScarlet** [comment]
yes, i just finished first version of my flow editor, look good so far
image

**Comment by jagenjo** [comment]
niiice, I would love to see it when it is ready

**Comment by lucasa** [comment]
@NateScarlet  Can you share how to use typescript?

**Pull request merged**
