### PR TITLE
midi slot fix (rename to i)

### PR DESCRIPTION
**Pull request by brucelane**

### CODE REVIEW

**Comment by jagenjo** [comment]
I already did it and push it today, thanks anyway

**Comment by brucelane** [comment]
nope, you forgot to rename slot to i line 1817

**Comment by jagenjo** [comment]
weird, I upload it after fixing the bug. Im having some issues with git today. some changes are not being commited, dont know why. Anyway, thanks for spotting the error.

**Comment by brucelane** [comment]
I think you fixed on line 1820 only?

**Comment by jagenjo** [comment]
ah yes, it was in two lines, my bad. for a second I was worried my changes werent being commited.

let me know if you see any strange thing, there are some bugs still that I dont know how to repeat

**Comment by brucelane** [comment]
muchas gracias!
I plan to put a background fullscreen canvas for a fragment shader and feed it for live-coding shaders!

**Comment by jagenjo** [comment]
nice, there are many nodes focused in processing textures, check the gltexture.js nodes, but keep in mind that they use my own webgl library called litegl.js

**Pull request merged**
